# Generated by Django 5.2.4 on 2025-07-23 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория'},
        ),
        migrations.AlterModelOptions(
            name='gallerycontent',
            options={'verbose_name': 'Галрей контент'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='image',
            field=models.ImageField(upload_to='gallery/GalleryContent', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle',
            field=models.TextField(verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_en',
            field=models.TextField(null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_ru',
            field=models.TextField(null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_tr',
            field=models.TextField(null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_uz',
            field=models.TextField(null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
