# Generated by Django 5.2.4 on 2025-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_alter_category_options_alter_gallerycontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle',
            field=models.TextField(default='GalleryContent subtitle', verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_en',
            field=models.TextField(default='GalleryContent subtitle', null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_ru',
            field=models.TextField(default='GalleryContent subtitle', null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_tr',
            field=models.TextField(default='GalleryContent subtitle', null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_uz',
            field=models.TextField(default='GalleryContent subtitle', null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title',
            field=models.CharField(default='GalleryContent title', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_en',
            field=models.CharField(default='GalleryContent title', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_ru',
            field=models.CharField(default='GalleryContent title', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_tr',
            field=models.CharField(default='GalleryContent title', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_uz',
            field=models.CharField(default='GalleryContent title', max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
