# Generated by Django 5.2.4 on 2025-08-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_alter_gallerycontent_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle',
            field=models.TextField(default='GalleryContent subtitle', null='true', verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title',
            field=models.CharField(max_length=200, null='true', verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
