# Generated by Django 5.2.4 on 2025-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0004_alter_gallerycontent_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gallerycontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle',
            field=models.TextField(blank=True, default='GalleryContent subtitle', null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_en',
            field=models.TextField(blank=True, default='GalleryContent subtitle', null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_ru',
            field=models.TextField(blank=True, default='GalleryContent subtitle', null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_tr',
            field=models.TextField(blank=True, default='GalleryContent subtitle', null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='subtitle_uz',
            field=models.TextField(blank=True, default='GalleryContent subtitle', null=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallerycontent',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
