# Generated by Django 5.2.4 on 2025-08-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0005_gallerycontent_created_at_gallerycontent_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycontent',
            options={'verbose_name': 'Галерея контент'},
        ),
    ]
