# Generated by Django 5.2.4 on 2025-07-23 05:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория'},
        ),
        migrations.AlterModelOptions(
            name='newscontent',
            options={'verbose_name': 'Новости контент'},
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='subtitle_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='subtitle_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='subtitle_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
