# Generated by Django 5.2.4 on 2025-07-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_category_options_alter_newscontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscontent',
            name='image',
            field=models.ImageField(upload_to='news/NewsContent'),
        ),
    ]
