# Generated by Django 5.2.4 on 2025-07-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('subtitle', models.TextField()),
                ('subtitle_uz', models.TextField(null=True)),
                ('subtitle_en', models.TextField(null=True)),
                ('subtitle_ru', models.TextField(null=True)),
                ('subtitle_tr', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='home/HomeContent')),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('full_name_uz', models.CharField(max_length=200, null=True)),
                ('full_name_en', models.CharField(max_length=200, null=True)),
                ('full_name_ru', models.CharField(max_length=200, null=True)),
                ('full_name_tr', models.CharField(max_length=200, null=True)),
                ('commint', models.TextField()),
                ('commint_uz', models.TextField(null=True)),
                ('commint_en', models.TextField(null=True)),
                ('commint_ru', models.TextField(null=True)),
                ('commint_tr', models.TextField(null=True)),
                ('author', models.ImageField(upload_to='home/TestimonialsContent')),
            ],
        ),
    ]
