# Generated by Django 5.2.4 on 2025-07-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecontent',
            options={'verbose_name': 'Главная контент'},
        ),
        migrations.AlterModelOptions(
            name='testimonialscontent',
            options={'verbose_name': 'Рекомендация контент'},
        ),
    ]
